import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import NextAuthSessionProvider from '@/providers/SessionProvider';
import { WebsocketStoreProvider } from '@/providers/WebsocketProvider';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
 title: 'Create Next App',
 description: 'Generated by create next app',
};

export default function RootLayout({
 children,
}: {
 children: React.ReactNode;
}) {
 return (
  <html lang='en'>
   <body className={inter.className}>
    <NextAuthSessionProvider>
     <main className='flex h-screen w-screen justify-center bg-bluedark'>
      <WebsocketStoreProvider>{children}</WebsocketStoreProvider>
     </main>
    </NextAuthSessionProvider>
   </body>
  </html>
 );
}
